#!/usr/bin/env python
# -*- coding: utf-8 -*-

##
## Feature and Written by Charles Barcza kbarcza@blackpanther.hu
##    blackPanther OS - www.blackpanther.hu
##


import sys, re, os, string, signal
import commands

from PyQt4 import QtCore, QtGui
#from kuick_ui import Kuick_UI

def lspcian(inp):
  net = ''
  for line in inp:
    if 'DISPLAY_VGA' in line:
      vga = line[line.find('|')+1:line.find('[')]
    elif 'NETWORK' in line:
      net += line[line.find('|')+1:line.rfind('[')]
  return [vga, net]

class GetInfo():
    def __init__(self):
      lspcidrake = lspcian(commands.getoutput('lspcidrake').split('\n'))
      self.system_os_name = commands.getoutput("cat /etc/blackPanther-release | awk -Frelease '{ print $1 }'")
      self.system_release = commands.getoutput("cat /etc/blackPanther-release | awk -Frelease '{ print $2 }'|sed 's|for.*||'")
      self.system_user_name = commands.getoutput("cat /etc/passwd | grep $USER| awk -F: '{ print $5\" \\n(\"$1\")\" }'")
      self.system_serial_name = commands.getoutput("cat /etc/sysconfig/edition-release | grep SN:")
      self.system_computer_name = commands.getoutput("uname -a|awk '{print $13\" \"$14\" (\"$2\")\"}'")
      self.system_processor_name = commands.getoutput("uname -p|awk '{print $4\" \"$5\" \"$6}'")
      self.system_memory_name = commands.getoutput("cat /proc/meminfo| grep MemTotal | awk -F: '{print $2}'| sed 's|       ||'")
      self.system_disks_name = commands.getoutput("cat /proc/partitions| sed -e 's|major.*||'|grep d| awk '{print $4 \" - \" $3}'")
      self.system_video_name = lspcidrake[0]
      self.system_netdevice_name = lspcidrake[1]
      
      self.network_computer_name = commands.getoutput("echo $HOSTNAME")
      self.network_workgroup_name = commands.getoutput("cat /etc/samba/smb.conf | sed 's|#.*||'|grep workgroup|awk -F= '{ print $2 }'|sed 's| ||'")
      self.network_samba_status = commands.getoutput("[[ -n $(pidof smbd 2>/dev/null) ]]&& echo Running ")
      self.network_share_level = commands.getoutput("cat /etc/samba/smb.conf | sed 's|#.*||'|grep security|awk -F= '{ print $2 }'|sed 's| ||'")
      self.network_computer_name = commands.getoutput("echo $HOSTNAME")
      self.network_firewall_state = 'Unknown'
      self.video_memory =  commands.getoutput("cat /var/log/Xorg.0.log|grep \"VideoRam\"|sed 's|.*: ||'| awk '{ print $1 \" \" $2 }'")
      self.video_driver =  commands.getoutput("cat /var/log/Xorg.0.log|grep \"Driver for\"|sed 's|.*) ||'| awk -F: '{ print $1 }'")
      self.rendering_support = commands.getoutput("glxinfo | grep 'direct rendering' | sed 's|^d|D|'")
      self.desktop_effects = commands.getoutput("[[ -n $(cat \"$HOME/.kde4/share/config/kwinrc\" | grep \"^Enabled=true\" ) ]] && echo Enabled")
      self.network_details = commands.getoutput("/sbin/ifconfig|grep Ethernet | sed 's|Link encap:Ethernet||'")
      
      
class MainWindow(QtGui.QMainWindow):
    def __init__(self):
        self.Info = GetInfo()
        QtGui.QMainWindow.__init__(self)

#class Ui_MyInfo(object):
#    def setupUi(self, MyInfo):
        MyInfo.setObjectName("MyInfo")
        MyInfo.resize(521, 538)
        MyInfo.setSizeGripEnabled(True)
        self.vboxlayout = QtGui.QVBoxLayout(MyInfo)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(11)
        self.vboxlayout.setObjectName("vboxlayout")
        self.tabWidget = QtGui.QTabWidget(MyInfo)
        self.tabWidget.setObjectName("tabWidget")
        self.Widget8 = QtGui.QWidget()
        self.Widget8.setObjectName("Widget8")
        self.groupBox = QtGui.QGroupBox(self.Widget8)
        self.groupBox.setGeometry(QtCore.QRect(220, 20, 251, 171))
        self.groupBox.setObjectName("groupBox")
        self.textLabel7 = QtGui.QLabel(self.groupBox)
        self.textLabel7.setGeometry(QtCore.QRect(10, 50, 90, 20))
        self.textLabel7.setWordWrap(False)
        self.textLabel7.setObjectName("textLabel7")
        self.os_name_text = QtGui.QLabel(self.groupBox)
        self.os_name_text.setGeometry(QtCore.QRect(90, 50, 100, 20))
        self.os_name_text.setWordWrap(False)
        self.os_name_text.setObjectName("os_name_text")
        self.textLabel9 = QtGui.QLabel(self.groupBox)
        self.textLabel9.setGeometry(QtCore.QRect(10, 70, 81, 20))
        self.textLabel9.setWordWrap(False)
        self.textLabel9.setObjectName("textLabel9")
        self.os_release_text = QtGui.QLabel(self.groupBox)
        self.os_release_text.setGeometry(QtCore.QRect(90, 70, 120, 20))
        self.os_release_text.setWordWrap(False)
        self.os_release_text.setObjectName("os_release_text")
        self.textLabel10 = QtGui.QLabel(self.groupBox)
        self.textLabel10.setGeometry(QtCore.QRect(10, 90, 61, 20))
        self.textLabel10.setWordWrap(False)
        self.textLabel10.setObjectName("textLabel10")
        self.os_user_text = QtGui.QLabel(self.groupBox)
        self.os_user_text.setGeometry(QtCore.QRect(90, 90, 151, 31))
        self.os_user_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.os_user_text.setWordWrap(False)
        self.os_user_text.setObjectName("os_user_text")
        self.textLabel8 = QtGui.QLabel(self.groupBox)
        self.textLabel8.setGeometry(QtCore.QRect(10, 120, 181, 20))
        self.textLabel8.setWordWrap(False)
        self.textLabel8.setObjectName("textLabel8")
        self.os_serial_text = QtGui.QLabel(self.groupBox)
        self.os_serial_text.setGeometry(QtCore.QRect(10, 140, 230, 20))
        self.os_serial_text.setWordWrap(False)
        self.os_serial_text.setObjectName("os_serial_text")
        self.groupBox_2 = QtGui.QGroupBox(self.Widget8)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 210, 461, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.progressBar = QtGui.QProgressBar(self.groupBox_2)
        self.progressBar.setGeometry(QtCore.QRect(30, 70, 191, 23))
        self.progressBar.setProperty("value", QtCore.QVariant(24))
        self.progressBar.setObjectName("progressBar")
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(30, 40, 61, 17))
        self.label.setObjectName("label")
        self.progressBar_2 = QtGui.QProgressBar(self.groupBox_2)
        self.progressBar_2.setGeometry(QtCore.QRect(250, 70, 191, 23))
        self.progressBar_2.setProperty("value", QtCore.QVariant(24))
        self.progressBar_2.setObjectName("progressBar_2")
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(250, 40, 101, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 91, 17))
        self.label_3.setObjectName("label_3")
        self.progressBar_3 = QtGui.QProgressBar(self.groupBox_2)
        self.progressBar_3.setGeometry(QtCore.QRect(30, 160, 191, 23))
        self.progressBar_3.setProperty("value", QtCore.QVariant(24))
        self.progressBar_3.setObjectName("progressBar_3")
        self.progressBar_4 = QtGui.QProgressBar(self.groupBox_2)
        self.progressBar_4.setEnabled(False)
        self.progressBar_4.setGeometry(QtCore.QRect(250, 160, 191, 23))
        self.progressBar_4.setProperty("value", QtCore.QVariant(24))
        self.progressBar_4.setObjectName("progressBar_4")
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(250, 130, 91, 17))
        self.label_4.setObjectName("label_4")
        self.frame = QtGui.QFrame(self.Widget8)
        self.frame.setGeometry(QtCore.QRect(19, 29, 181, 161))
        self.frame.setStyleSheet("background-image: url(pics/logo.png);")
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tabWidget.addTab(self.Widget8, "")
        self.TabPage = QtGui.QWidget()
        self.TabPage.setObjectName("TabPage")
        self.system_disks_name_text = QtGui.QGroupBox(self.TabPage)
        self.system_disks_name_text.setGeometry(QtCore.QRect(10, 230, 461, 201))
        self.system_disks_name_text.setObjectName("system_disks_name_text")
        self.textLabel2 = QtGui.QLabel(self.system_disks_name_text)
        self.textLabel2.setGeometry(QtCore.QRect(20, 30, 100, 20))
        self.textLabel2.setWordWrap(False)
        self.textLabel2.setObjectName("textLabel2")
        self.textLabel3 = QtGui.QLabel(self.system_disks_name_text)
        self.textLabel3.setGeometry(QtCore.QRect(20, 50, 100, 20))
        self.textLabel3.setWordWrap(False)
        self.textLabel3.setObjectName("textLabel3")
        self.textLabel4 = QtGui.QLabel(self.system_disks_name_text)
        self.textLabel4.setGeometry(QtCore.QRect(20, 70, 100, 20))
        self.textLabel4.setWordWrap(False)
        self.textLabel4.setObjectName("textLabel4")
        self.textLabel5 = QtGui.QLabel(self.system_disks_name_text)
        self.textLabel5.setGeometry(QtCore.QRect(20, 90, 100, 20))
        self.textLabel5.setWordWrap(False)
        self.textLabel5.setObjectName("textLabel5")
        self.textLabel12 = QtGui.QLabel(self.system_disks_name_text)
        self.textLabel12.setGeometry(QtCore.QRect(20, 140, 100, 20))
        self.textLabel12.setWordWrap(False)
        self.textLabel12.setObjectName("textLabel12")
        self.textLabel6 = QtGui.QLabel(self.system_disks_name_text)
        self.textLabel6.setGeometry(QtCore.QRect(20, 160, 100, 20))
        self.textLabel6.setWordWrap(False)
        self.textLabel6.setObjectName("textLabel6")
        self.system_computer_name_text = QtGui.QLabel(self.system_disks_name_text)
        self.system_computer_name_text.setGeometry(QtCore.QRect(150, 30, 261, 20))
        self.system_computer_name_text.setWordWrap(False)
        self.system_computer_name_text.setObjectName("system_computer_name_text")
        self.system_processor_name_text = QtGui.QLabel(self.system_disks_name_text)
        self.system_processor_name_text.setGeometry(QtCore.QRect(150, 50, 261, 20))
        self.system_processor_name_text.setWordWrap(False)
        self.system_processor_name_text.setObjectName("system_processor_name_text")
        self.system_memory_name_text = QtGui.QLabel(self.system_disks_name_text)
        self.system_memory_name_text.setGeometry(QtCore.QRect(150, 70, 261, 20))
        self.system_memory_name_text.setWordWrap(False)
        self.system_memory_name_text.setObjectName("system_memory_name_text")
        self.system_memory_name_text_2 = QtGui.QLabel(self.system_disks_name_text)
        self.system_memory_name_text_2.setGeometry(QtCore.QRect(150, 90, 301, 41))
        self.system_memory_name_text_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.system_memory_name_text_2.setWordWrap(False)
        self.system_memory_name_text_2.setObjectName("system_memory_name_text_2")

        self.system_video_name_text = QtGui.QLabel(self.system_disks_name_text)
        self.system_video_name_text.setGeometry(QtCore.QRect(150, 140, 261, 20))
        self.system_video_name_text.setWordWrap(False)
        self.system_video_name_text.setObjectName("system_video_name_text")

        self.system_netdevice_name_text = QtGui.QLabel(self.system_disks_name_text)
        self.system_netdevice_name_text.setGeometry(QtCore.QRect(150, 160, 281, 20))
        self.system_netdevice_name_text.setWordWrap(False)
        self.system_netdevice_name_text.setObjectName("system_netdevice_name_text")

        self.hardware_reviews = QtGui.QGroupBox(self.TabPage)
        self.hardware_reviews.setGeometry(QtCore.QRect(10, 10, 461, 201))
        self.hardware_reviews.setObjectName("hardware_reviews")

        self.device_manager_button = QtGui.QPushButton(self.hardware_reviews)
        self.device_manager_button.setGeometry(QtCore.QRect(260, 130, 180, 31))
        self.device_manager_button.setObjectName("device_manager_button")
        self.connect(self.device_manager_button,QtCore.SIGNAL("clicked()"),self.slotDevManButton)

        self.textLabel13 = QtGui.QLabel(self.hardware_reviews)
        self.textLabel13.setGeometry(QtCore.QRect(150, 30, 291, 60))
        self.textLabel13.setWordWrap(False)
        self.textLabel13.setObjectName("textLabel13")

        self.hardw_page_logo = QtGui.QFrame(self.hardware_reviews)
        self.hardw_page_logo.setGeometry(QtCore.QRect(10, 20, 125, 125))
        self.hardw_page_logo.setStyleSheet("background-image: url(pics/hwinfo.png);")
        self.hardw_page_logo.setFrameShape(QtGui.QFrame.StyledPanel)
        self.hardw_page_logo.setFrameShadow(QtGui.QFrame.Raised)
        self.hardw_page_logo.setObjectName("hardw_page_logo")

        self.tabWidget.addTab(self.TabPage, "")
        self.TabPage1 = QtGui.QWidget()
        self.TabPage1.setObjectName("TabPage1")
        self.pushButton7_2 = QtGui.QPushButton(self.TabPage1)
        self.pushButton7_2.setEnabled(False)
        self.pushButton7_2.setGeometry(QtCore.QRect(20, 430, 130, 20))
        self.pushButton7_2.setObjectName("pushButton7_2")
        self.pushButton8 = QtGui.QPushButton(self.TabPage1)
        self.pushButton8.setEnabled(False)
        self.pushButton8.setGeometry(QtCore.QRect(180, 430, 140, 20))
        self.pushButton8.setObjectName("pushButton8")
        self.pushButton9_2 = QtGui.QPushButton(self.TabPage1)
        self.pushButton9_2.setGeometry(QtCore.QRect(340, 429, 130, 21))
        self.pushButton9_2.setObjectName("pushButton9_2")
        self.treeView = QtGui.QTreeView(self.TabPage1)
        self.treeView.setEnabled(False)
        self.treeView.setGeometry(QtCore.QRect(20, 10, 451, 401))
        self.treeView.setObjectName("treeView")
        self.tabWidget.addTab(self.TabPage1, "")
        self.Widget9 = QtGui.QWidget()
        self.Widget9.setObjectName("Widget9")
        self.groupBox7 = QtGui.QGroupBox(self.Widget9)
        self.groupBox7.setGeometry(QtCore.QRect(17, 227, 451, 201))
        self.groupBox7.setObjectName("groupBox7")

        self.netdev_config_button = QtGui.QPushButton(self.groupBox7)
        self.netdev_config_button.setGeometry(QtCore.QRect(310, 80, 110, 20))
        self.netdev_config_button.setObjectName("netdev_config_button")
        self.connect(self.netdev_config_button,QtCore.SIGNAL("clicked()"),self.slotDevConfig)

        self.netdev_macchg_button = QtGui.QPushButton(self.groupBox7)
        self.netdev_macchg_button.setGeometry(QtCore.QRect(310, 110, 110, 20))
        self.netdev_macchg_button.setObjectName("netdev_macchg_button")
        self.connect(self.netdev_macchg_button,QtCore.SIGNAL("clicked()"),self.slotMacConfig)

        self.network_wakeon_button = QtGui.QPushButton(self.groupBox7)
        self.network_wakeon_button.setGeometry(QtCore.QRect(310, 140, 110, 20))
        self.network_wakeon_button.setObjectName("network_wakeon_button")
        self.connect(self.network_wakeon_button,QtCore.SIGNAL("clicked()"),self.slotWakeOnLan)

        self.network_details = QtGui.QLabel(self.groupBox7)
        self.network_details.setGeometry(QtCore.QRect(20, 40, 280, 100))
        self.network_details.setWordWrap(False)
        self.network_details.setObjectName("network_details")

        self.groupBox6 = QtGui.QGroupBox(self.Widget9)
        self.groupBox6.setGeometry(QtCore.QRect(17, 18, 451, 201))
        self.groupBox6.setObjectName("groupBox6")
        self.textLabel4_2 = QtGui.QLabel(self.groupBox6)
        self.textLabel4_2.setGeometry(QtCore.QRect(20, 120, 91, 20))
        self.textLabel4_2.setWordWrap(False)
        self.textLabel4_2.setObjectName("textLabel4_2")
        self.textLabel3_2 = QtGui.QLabel(self.groupBox6)
        self.textLabel3_2.setGeometry(QtCore.QRect(20, 90, 150, 20))
        self.textLabel3_2.setWordWrap(False)
        self.textLabel3_2.setObjectName("textLabel3_2")
        self.textLabel2_2 = QtGui.QLabel(self.groupBox6)
        self.textLabel2_2.setGeometry(QtCore.QRect(20, 60, 91, 20))
        self.textLabel2_2.setWordWrap(False)
        self.textLabel2_2.setObjectName("textLabel2_2")
        self.textLabel1 = QtGui.QLabel(self.groupBox6)
        self.textLabel1.setGeometry(QtCore.QRect(20, 30, 111, 20))
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.network_computer_name_text = QtGui.QLabel(self.groupBox6)
        self.network_computer_name_text.setGeometry(QtCore.QRect(140, 30, 201, 20))
        self.network_computer_name_text.setWordWrap(False)
        self.network_computer_name_text.setObjectName("network_computer_name_text")
        self.network_workgroup_name_text = QtGui.QLabel(self.groupBox6)
        self.network_workgroup_name_text.setGeometry(QtCore.QRect(140, 60, 241, 20))
        self.network_workgroup_name_text.setWordWrap(False)
        self.network_workgroup_name_text.setObjectName("network_workgroup_name_text")
        self.network_samba_status_text = QtGui.QLabel(self.groupBox6)
        self.network_samba_status_text.setGeometry(QtCore.QRect(140, 90, 271, 20))
        self.network_samba_status_text.setWordWrap(False)
        self.network_samba_status_text.setObjectName("network_samba_status_text")
        self.network_share_level_text = QtGui.QLabel(self.groupBox6)
        self.network_share_level_text.setGeometry(QtCore.QRect(140, 120, 271, 20))
        self.network_share_level_text.setWordWrap(False)
        self.network_share_level_text.setObjectName("network_share_level_text")
        self.textLabel1_6 = QtGui.QLabel(self.groupBox6)
        self.textLabel1_6.setGeometry(QtCore.QRect(20, 150, 91, 20))
        self.textLabel1_6.setWordWrap(False)
        self.textLabel1_6.setObjectName("textLabel1_6")
        self.network_firewall_state_text = QtGui.QLabel(self.groupBox6)
        self.network_firewall_state_text.setGeometry(QtCore.QRect(140, 150, 281, 20))
        self.network_firewall_state_text.setWordWrap(False)
        self.network_firewall_state_text.setObjectName("network_firewall_state_text")
        self.tabWidget.addTab(self.Widget9, "")
        self.TabPage2 = QtGui.QWidget()
        self.TabPage2.setObjectName("TabPage2")
        self.groupBox5 = QtGui.QGroupBox(self.TabPage2)
        self.groupBox5.setGeometry(QtCore.QRect(10, 340, 470, 91))
        self.groupBox5.setObjectName("groupBox5")
        self.groupBox4 = QtGui.QGroupBox(self.TabPage2)
        self.groupBox4.setGeometry(QtCore.QRect(10, 20, 470, 291))
        self.groupBox4.setObjectName("groupBox4")
        self.textLabel6_2 = QtGui.QLabel(self.groupBox4)
        self.textLabel6_2.setGeometry(QtCore.QRect(30, 60, 410, 20))
        self.textLabel6_2.setWordWrap(False)
        self.textLabel6_2.setObjectName("textLabel6_2")
        self.textLabel5_2 = QtGui.QLabel(self.groupBox4)
        self.textLabel5_2.setGeometry(QtCore.QRect(30, 30, 410, 20))
        self.textLabel5_2.setWordWrap(False)
        self.textLabel5_2.setObjectName("textLabel5_2")
        self.textLabel7_2 = QtGui.QLabel(self.groupBox4)
        self.textLabel7_2.setGeometry(QtCore.QRect(30, 90, 410, 20))
        self.textLabel7_2.setWordWrap(False)               
        self.textLabel7_2.setObjectName("textLabel7_2")
        self.textLabel8_2 = QtGui.QLabel(self.groupBox4)
        self.textLabel8_2.setGeometry(QtCore.QRect(30, 120, 410, 20))
        self.textLabel8_2.setWordWrap(False)
        self.textLabel8_2.setObjectName("textLabel8_2")
        self.tabWidget.addTab(self.TabPage2, "")
        self.vboxlayout.addWidget(self.tabWidget)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.buttonHelp = QtGui.QPushButton(MyInfo)
        self.buttonHelp.setAutoDefault(True)
        self.buttonHelp.setObjectName("buttonHelp")
        self.hboxlayout.addWidget(self.buttonHelp)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.buttonOk = QtGui.QPushButton(MyInfo)
        self.buttonOk.setEnabled(False)
        self.buttonOk.setAutoDefault(True)
        self.buttonOk.setDefault(True)
        self.buttonOk.setObjectName("buttonOk")
        self.hboxlayout.addWidget(self.buttonOk)
        self.buttonCancel = QtGui.QPushButton(MyInfo)
        self.buttonCancel.setAutoDefault(True)
        self.buttonCancel.setObjectName("buttonCancel")
        self.hboxlayout.addWidget(self.buttonCancel)
        self.vboxlayout.addLayout(self.hboxlayout)

        self.retranslateUi(MyInfo)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonOk, QtCore.SIGNAL("clicked()"), MyInfo.accept)
        QtCore.QObject.connect(self.buttonCancel, QtCore.SIGNAL("clicked()"), MyInfo.reject)
        QtCore.QMetaObject.connectSlotsByName(MyInfo)

    def retranslateUi(self, MyInfo):
        MyInfo.setWindowTitle(QtGui.QApplication.translate("MyInfo", "blackPanther OS MyInfo", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MyInfo", "System infromations", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel7.setText(QtGui.QApplication.translate("MyInfo", "<b>OS name:</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.os_name_text.setText(QtGui.QApplication.translate("MyInfo", self.Info.system_os_name, None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel9.setText(QtGui.QApplication.translate("MyInfo", "<b>Release:</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.os_release_text.setText(QtGui.QApplication.translate("MyInfo", self.Info.system_release, None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel10.setText(QtGui.QApplication.translate("MyInfo", "<b>User:</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.os_user_text.setText(QtGui.QApplication.translate("MyInfo", self.Info.system_user_name, None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel8.setText(QtGui.QApplication.translate("MyInfo", "<b>Serial number:</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.os_serial_text.setText(QtGui.QApplication.translate("MyInfo", self.Info.system_serial_name, None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MyInfo", "System usage", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MyInfo", "CPU usage", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MyInfo", "Memory usage", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MyInfo", "Wireless signal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MyInfo", "Other load", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Widget8), QtGui.QApplication.translate("MyInfo", "Main page", None, QtGui.QApplication.UnicodeUTF8))
        self.system_disks_name_text.setTitle(QtGui.QApplication.translate("MyInfo", "System review", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2.setText(QtGui.QApplication.translate("MyInfo", "<b>Computer:</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel3.setText(QtGui.QApplication.translate("MyInfo", "<b>Processor:</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4.setText(QtGui.QApplication.translate("MyInfo", "<b>Memory:</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel5.setText(QtGui.QApplication.translate("MyInfo", "<b>Disks:</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel12.setText(QtGui.QApplication.translate("MyInfo", "<b>Video:</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel6.setText(QtGui.QApplication.translate("MyInfo", "<b>Network  device:</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.system_computer_name_text.setText(QtGui.QApplication.translate("MyInfo", self.Info.system_computer_name, None, QtGui.QApplication.UnicodeUTF8))
        self.system_processor_name_text.setText(QtGui.QApplication.translate("MyInfo", self.Info.system_processor_name, None, QtGui.QApplication.UnicodeUTF8))
        self.system_memory_name_text.setText(QtGui.QApplication.translate("MyInfo", self.Info.system_memory_name, None, QtGui.QApplication.UnicodeUTF8))
        self.system_memory_name_text_2.setText(QtGui.QApplication.translate("MyInfo", self.Info.system_disks_name, None, QtGui.QApplication.UnicodeUTF8))
        self.system_video_name_text.setText(QtGui.QApplication.translate("MyInfo", self.Info.system_video_name, None, QtGui.QApplication.UnicodeUTF8))
        self.system_netdevice_name_text.setText(QtGui.QApplication.translate("MyInfo", self.Info.system_netdevice_name, None, QtGui.QApplication.UnicodeUTF8))
        self.hardware_reviews.setTitle(QtGui.QApplication.translate("MyInfo", "Hardwares reviews", None, QtGui.QApplication.UnicodeUTF8))
        self.device_manager_button.setText(QtGui.QApplication.translate("MyInfo", "Device manager", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel13.setText(QtGui.QApplication.translate("MyInfo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Toga Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:x-large; font-weight:600;\"><span style=\" font-size:x-large;\">Here available the device </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:x-large; font-weight:600;\"><span style=\" font-size:x-large;\">configuration tool...</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabPage), QtGui.QApplication.translate("MyInfo", "Hardwares", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton7_2.setText(QtGui.QApplication.translate("MyInfo", "Propeties", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton8.setText(QtGui.QApplication.translate("MyInfo", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton9_2.setText(QtGui.QApplication.translate("MyInfo", "Add new ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabPage1), QtGui.QApplication.translate("MyInfo", "Device manager", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox7.setTitle(QtGui.QApplication.translate("MyInfo", "Configuration and Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.netdev_config_button.setText(QtGui.QApplication.translate("MyInfo", "Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.netdev_macchg_button.setText(QtGui.QApplication.translate("MyInfo", "Mac change", None, QtGui.QApplication.UnicodeUTF8))
        self.network_wakeon_button.setText(QtGui.QApplication.translate("MyInfo", "WakeOn", None, QtGui.QApplication.UnicodeUTF8))
        self.network_details.setText(QtGui.QApplication.translate("MyInfo", "Network Devices Details: \n\n" + self.Info.network_details , None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox6.setTitle(QtGui.QApplication.translate("MyInfo", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4_2.setText(QtGui.QApplication.translate("MyInfo", "Share level:", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel3_2.setText(QtGui.QApplication.translate("MyInfo", "Samba status:", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2_2.setText(QtGui.QApplication.translate("MyInfo", "Workgroup:", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1.setText(QtGui.QApplication.translate("MyInfo", "Computer name:", None, QtGui.QApplication.UnicodeUTF8))
        self.network_computer_name_text.setText(QtGui.QApplication.translate("MyInfo", self.Info.network_computer_name, None, QtGui.QApplication.UnicodeUTF8))
        self.network_workgroup_name_text.setText(QtGui.QApplication.translate("MyInfo",  self.Info.network_workgroup_name, None, QtGui.QApplication.UnicodeUTF8))
        self.network_samba_status_text.setText(QtGui.QApplication.translate("MyInfo", self.Info.network_samba_status, None, QtGui.QApplication.UnicodeUTF8))
        self.network_share_level_text.setText(QtGui.QApplication.translate("MyInfo", self.Info.network_share_level, None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_6.setText(QtGui.QApplication.translate("MyInfo", "Firewall state:", None, QtGui.QApplication.UnicodeUTF8))
        self.network_firewall_state_text.setText(QtGui.QApplication.translate("MyInfo", self.Info.network_firewall_state, None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Widget9), QtGui.QApplication.translate("MyInfo", "Network", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox5.setTitle(QtGui.QApplication.translate("MyInfo", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox4.setTitle(QtGui.QApplication.translate("MyInfo", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel6_2.setText(QtGui.QApplication.translate("MyInfo", "Used Video Driver: " + self.Info.video_driver, None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel5_2.setText(QtGui.QApplication.translate("MyInfo", "Available Video Memory: " + self.Info.video_memory, None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel7_2.setText(QtGui.QApplication.translate("MyInfo", "Use 3D " + self.Info.rendering_support, None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel8_2.setText(QtGui.QApplication.translate("MyInfo", "Used Dektop Effects: " + self.Info.desktop_effects, None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabPage2), QtGui.QApplication.translate("MyInfo", "Performance", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonHelp.setText(QtGui.QApplication.translate("MyInfo", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonHelp.setShortcut(QtGui.QApplication.translate("MyInfo", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonOk.setText(QtGui.QApplication.translate("MyInfo", "&OK", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonCancel.setText(QtGui.QApplication.translate("MyInfo", "Exit", None, QtGui.QApplication.UnicodeUTF8))

#import MyInfo_rc

#-----------------------------------------------------------------------------------------
# New features
#-----------------------------------------------------------------------------------------


    def slotDevManButton(self):
        print "Launch device manager... \n>"
        os.popen("/usr/sbin/harddrake2")
        
    def slotDeleteDev(self):
        print "UI slotDeleteDev(): Not implemented yet\n>"

    def slotDevConfig(self):
        print "Launch network configure... \n>"
        os.popen("draknetcenter")

    def slotMacConfig(self):
        print "Launch MAC configure... \n>"
        os.popen("./makchanger.py")

    def slotWakeOnLan(self):
        print "Launc Wake On Lan... \n>"
        os.popen("./kwakeonlan.py")

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MyInfo = QtGui.QDialog()
    ui = MainWindow()
    #ui = Ui_MyInfo()
    #ui.setupUi(MyInfo)
    MyInfo.show()
    sys.exit(app.exec_())
