#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from recommendWidget_tab2.ui on Thu Jul 10 18:23:28 2014
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_recommendWidget(object):
    def setupUi(self, recommendWidget):
        recommendWidget.setObjectName(_fromUtf8("recommendWidget"))
        recommendWidget.resize(586, 542)
        self.gridLayout = QtGui.QGridLayout(recommendWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(recommendWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.East)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setEnabled(True)
        self.tab1.setCursor(QtCore.Qt.PointingHandCursor)
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.listRecommendApp = QtGui.QListWidget(self.tab1)
        self.listRecommendApp.setGeometry(QtCore.QRect(0, 0, 511, 411))
        self.listRecommendApp.setMinimumSize(QtCore.QSize(0, 300))
        self.listRecommendApp.setStyleSheet(_fromUtf8("#listRecommendApp{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 81), stop:0.00537634 rgba(0, 0, 0, 80), stop:1 rgba(250, 250, 230, 80));\n"
"\n"
"border: 1px solid rgb(236, 236, 236, 80);}"))
        self.listRecommendApp.setFrameShape(QtGui.QFrame.NoFrame)
        self.listRecommendApp.setFrameShadow(QtGui.QFrame.Sunken)
        self.listRecommendApp.setAlternatingRowColors(False)
        self.listRecommendApp.setTextElideMode(QtCore.Qt.ElideRight)
        self.listRecommendApp.setProperty(_fromUtf8("isWrapping"), False)
        self.listRecommendApp.setResizeMode(QtGui.QListView.Fixed)
        self.listRecommendApp.setLayoutMode(QtGui.QListView.SinglePass)
        self.listRecommendApp.setSpacing(0)
        self.listRecommendApp.setGridSize(QtCore.QSize(0, 110))
        self.listRecommendApp.setViewMode(QtGui.QListView.ListMode)
        self.listRecommendApp.setModelColumn(0)
        self.listRecommendApp.setUniformItemSizes(False)
        self.listRecommendApp.setBatchSize(100)
        self.listRecommendApp.setObjectName(_fromUtf8("listRecommendApp"))
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushUpdateButton = QtGui.QPushButton(recommendWidget)
        self.pushUpdateButton.setObjectName(_fromUtf8("pushUpdateButton"))
        self.horizontalLayout.addWidget(self.pushUpdateButton)
        self.labelUpdate = QtGui.QLabel(recommendWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(10)
        self.labelUpdate.setFont(font)
        self.labelUpdate.setText(_fromUtf8(""))
        self.labelUpdate.setObjectName(_fromUtf8("labelUpdate"))
        self.horizontalLayout.addWidget(self.labelUpdate)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.checkBox = QtGui.QCheckBox(recommendWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 4, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 4, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 5, 1, 1, 1)
        self.label = QtGui.QLabel(recommendWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(25)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setStyleSheet(_fromUtf8(""))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(recommendWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)

        self.retranslateUi(recommendWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(recommendWidget)

    def retranslateUi(self, recommendWidget):
        recommendWidget.setWindowTitle(kdecore.i18n("Recommend"))
        recommendWidget.setStyleSheet(kdecore.i18n("color: rgb(234, 225, 228);"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), kdecore.i18n("Default"))
        self.pushUpdateButton.setToolTip(kdecore.i18n("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Here you can download fresh recommend </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">application\'s list from blackPanther servers...</span></p></body></html>"))
        self.pushUpdateButton.setText(kdecore.i18n("Update list from Internet"))
        self.checkBox.setToolTip(kdecore.i18n("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">If don\'t want installing plugins or applications, </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">check this box... The plugins need to more applications,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">like flash-player to can watch videos on Internet.</span></p></body></html>"))
        self.checkBox.setText(kdecore.i18n("Skip this step"))
        self.label.setText(kdecore.i18n("Choose Recommend Apps"))
        self.label_2.setText(kdecore.i18n("Can find more suggested apps for your perfect system"))


def encode(text):
    return text.encode('utf-8')
    