#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from searchWidget.ui on Sat Jul  5 10:25:11 2014
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_searchWidget(object):
    def setupUi(self, searchWidget):
        searchWidget.setObjectName(_fromUtf8("searchWidget"))
        searchWidget.resize(602, 513)
        self.gridLayout = QtGui.QGridLayout(searchWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(searchWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(25)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet(_fromUtf8(""))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(20, 50, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelSearchDescription = QtGui.QLabel(searchWidget)
        self.labelSearchDescription.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(11)
        self.labelSearchDescription.setFont(font)
        self.labelSearchDescription.setStyleSheet(_fromUtf8(""))
        self.labelSearchDescription.setFrameShadow(QtGui.QFrame.Raised)
        self.labelSearchDescription.setWordWrap(True)
        self.labelSearchDescription.setObjectName(_fromUtf8("labelSearchDescription"))
        self.horizontalLayout.addWidget(self.labelSearchDescription)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.checkBoxNepomuk = QtGui.QCheckBox(searchWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(11)
        self.checkBoxNepomuk.setFont(font)
        self.checkBoxNepomuk.setStyleSheet(_fromUtf8("color: rgb(234, 225, 228);"))
        self.checkBoxNepomuk.setChecked(False)
        self.checkBoxNepomuk.setObjectName(_fromUtf8("checkBoxNepomuk"))
        self.verticalLayout.addWidget(self.checkBoxNepomuk)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 3, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 0, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 0, 1, 1)

        self.retranslateUi(searchWidget)
        QtCore.QMetaObject.connectSlotsByName(searchWidget)

    def retranslateUi(self, searchWidget):
        searchWidget.setWindowTitle(kdecore.i18n("Search"))
        searchWidget.setStyleSheet(kdecore.i18n("color: rgb(234, 225, 228);"))
        self.label.setText(kdecore.i18n("Easy Desktop Search"))
        self.labelSearchDescription.setText(kdecore.i18n("Strigi Desktop Search indexes your frequently used files. This gives you very fast file search results. Strigi also can search for files based on their contents. (Warning! Not recommended for old/slow PC)"))
        self.checkBoxNepomuk.setText(kdecore.i18n("Allow Strigi to index my files"))


def encode(text):
    return text.encode('utf-8')
    