#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from sr./module_gui/smoltWidget.ui on Wed Jul  2 19:58:37 2014
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_smoltWidget(object):
    def setupUi(self, smoltWidget):
        smoltWidget.setObjectName(_fromUtf8("smoltWidget"))
        smoltWidget.resize(616, 539)
        self.gridLayout_4 = QtGui.QGridLayout(smoltWidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 7, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem2 = QtGui.QSpacerItem(538, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 3)
        self.checkBox = QtGui.QCheckBox(smoltWidget)
        self.checkBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 1, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        self.privacyButton = QtGui.QPushButton(smoltWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.privacyButton.sizePolicy().hasHeightForWidth())
        self.privacyButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(10)
        self.privacyButton.setFont(font)
        self.privacyButton.setObjectName(_fromUtf8("privacyButton"))
        self.gridLayout.addWidget(self.privacyButton, 1, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 4, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 7, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 7, 2, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(smoltWidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.profilePage = QtGui.QWidget()
        self.profilePage.setObjectName(_fromUtf8("profilePage"))
        self.gridLayout_2 = QtGui.QGridLayout(self.profilePage)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tableWidget = QtGui.QTableWidget(self.profilePage)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.profilePage)
        self.privacyPage = QtGui.QWidget()
        self.privacyPage.setObjectName(_fromUtf8("privacyPage"))
        self.gridLayout_3 = QtGui.QGridLayout(self.privacyPage)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.textEdit = QtGui.QTextEdit(self.privacyPage)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_3.addWidget(self.textEdit, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.privacyPage)
        self.gridLayout_4.addWidget(self.stackedWidget, 6, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem7, 8, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem8, 5, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem9, 3, 1, 1, 1)
        self.label = QtGui.QLabel(smoltWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(25)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 2, 1, 1, 1)
        self.labelMouseDesc = QtGui.QLabel(smoltWidget)
        self.labelMouseDesc.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(11)
        self.labelMouseDesc.setFont(font)
        self.labelMouseDesc.setStyleSheet(_fromUtf8(""))
        self.labelMouseDesc.setWordWrap(True)
        self.labelMouseDesc.setObjectName(_fromUtf8("labelMouseDesc"))
        self.gridLayout_4.addWidget(self.labelMouseDesc, 4, 1, 1, 1)

        self.retranslateUi(smoltWidget)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(smoltWidget)

    def retranslateUi(self, smoltWidget):
        smoltWidget.setWindowTitle(kdecore.i18n("Smolt"))
        smoltWidget.setStyleSheet(kdecore.i18n("color: rgb(234, 225, 228);"))
        self.checkBox.setStyleSheet(kdecore.i18n("color: rgb(234, 225, 228);"))
        self.checkBox.setText(kdecore.i18n("&Send my profile"))
        self.privacyButton.setStyleSheet(kdecore.i18n("color:rgb(95, 34, 52)"))
        self.privacyButton.setText(kdecore.i18n("&Privacy policy"))
        self.tableWidget.setStyleSheet(kdecore.i18n("color: rgb(95, 34, 52);"))
        self.textEdit.setStyleSheet(kdecore.i18n("color: rgb(95, 34, 52);"))
        self.textEdit.setHtml(kdecore.i18n("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">   Smolt will only send hardware and basic operating system information to the blackPanther OS smolt server (smoon).  The only tie from the database to a submitters machine is the UUID.  As long as the submitter does not give out this UUID the submission is anonymous.  If at any point in time a user wants to delete their profile from the database they need only run</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">    </span><span style=\" font-size:9pt; font-style:italic;\">smoltDeleteProfile</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">   The information sent to the smolt database server should be considered public in that anyone can view the statistics, data and share machine profiles.  In  many ways smolt is designed to get hardware vendors and other 3rd parties attention.  As such, not only will this information be shared with 3rd parties, we will be using smolt as leverage to gain better support for open source drivers and better support in general.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; text-decoration: underline;\">IP Logging:</span><span style=\" font-size:9pt;\">  In blackPanther OS\'s smolt install all web traffic goes through a proxy server first.  This is the only place IP addresses are being logged and they are kept on that server for a period of 4 weeks at which time log rotation removes these logs.  The blackPanther OS Project does not aggregate ip addresses in the smolt database.  These logs are private and will not be available to the general public.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">   Users unhappy with this policy should simply not use smolt.  Users with questions about this policy should contact the blackPanther OS Infrastructure Team at admin [at] pardus.org.tr  Also remember that users can delete their profiles at any time using \"</span><span style=\" font-size:9pt; font-style:italic;\">smoltDeleteProfile</span><span style=\" font-size:9pt;\">\"</span></p></body></html>"))
        self.label.setText(kdecore.i18n("Help blackPanther OS Improve!"))
        self.labelMouseDesc.setText(kdecore.i18n("<b>Smolt</b> is a tool that collects the information in the following table and sends it to us for which lets us improve blackPanther OS according to the user profile statistics."))


def encode(text):
    return text.encode('utf-8')
    