#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from sr./module_gui/styleitem.ui on Wed Jul  2 19:58:37 2014
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_StyleItemWidget(object):
    def setupUi(self, StyleItemWidget):
        StyleItemWidget.setObjectName(_fromUtf8("StyleItemWidget"))
        StyleItemWidget.resize(560, 90)
        StyleItemWidget.setMinimumSize(QtCore.QSize(0, 90))
        self.gridLayout = QtGui.QGridLayout(StyleItemWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.stylePreview = QtGui.QLabel(StyleItemWidget)
        self.stylePreview.setMinimumSize(QtCore.QSize(111, 90))
        self.stylePreview.setMaximumSize(QtCore.QSize(111, 90))
        self.stylePreview.setText(_fromUtf8(""))
        self.stylePreview.setPixmap(QtGui.QPixmap(_fromUtf8("./module_gui/pics/logo2010.png")))
        self.stylePreview.setScaledContents(True)
        self.stylePreview.setObjectName(_fromUtf8("stylePreview"))
        self.gridLayout.addWidget(self.stylePreview, 0, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(15, 5, 15, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.styleName = QtGui.QLabel(StyleItemWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.styleName.setFont(font)
        self.styleName.setObjectName(_fromUtf8("styleName"))
        self.verticalLayout.addWidget(self.styleName)
        self.styleDesc = QtGui.QLabel(StyleItemWidget)
        self.styleDesc.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(10)
        self.styleDesc.setFont(font)
        self.styleDesc.setStyleSheet(_fromUtf8(""))
        self.styleDesc.setWordWrap(True)
        self.styleDesc.setObjectName(_fromUtf8("styleDesc"))
        self.verticalLayout.addWidget(self.styleDesc)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(313, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)

        self.retranslateUi(StyleItemWidget)
        QtCore.QMetaObject.connectSlotsByName(StyleItemWidget)

    def retranslateUi(self, StyleItemWidget):
        StyleItemWidget.setWindowTitle(kdecore.i18n("Form"))
        self.stylePreview.setStyleSheet(kdecore.i18n("border: 1px solid rgb(236, 236, 236, 100);"))
        self.styleName.setText(kdecore.i18n("styleName"))
        self.styleDesc.setText(kdecore.i18n("styleDesc"))


def encode(text):
    return text.encode('utf-8')
    