#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from styleWidget.ui on Fri Jul 11 07:35:20 2014
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_styleWidget(object):
    def setupUi(self, styleWidget):
        styleWidget.setObjectName(_fromUtf8("styleWidget"))
        styleWidget.resize(600, 521)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(11)
        styleWidget.setFont(font)
        self.gridLayout = QtGui.QGridLayout(styleWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label = QtGui.QLabel(styleWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        spacerItem3 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem3)
        self.labelMouseDesc = QtGui.QLabel(styleWidget)
        self.labelMouseDesc.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.labelMouseDesc.setFont(font)
        self.labelMouseDesc.setStyleSheet(_fromUtf8("color: rgb(234, 225, 228);"))
        self.labelMouseDesc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelMouseDesc.setWordWrap(True)
        self.labelMouseDesc.setObjectName(_fromUtf8("labelMouseDesc"))
        self.verticalLayout.addWidget(self.labelMouseDesc)
        spacerItem4 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.listStyles = QtGui.QListWidget(styleWidget)
        self.listStyles.setMinimumSize(QtCore.QSize(0, 300))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.listStyles.setFont(font)
        self.listStyles.setStyleSheet(_fromUtf8("#listStyles{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 81), stop:0.00537634 rgba(0, 0, 0, 80), stop:1 rgba(250, 250, 230, 80));\n"
"\n"
"border: 1px solid rgb(236, 236, 236, 80);\n"
"\n"
"color: rgb(23, 225, 228);\n"
"}"))
        self.listStyles.setObjectName(_fromUtf8("listStyles"))
        self.verticalLayout.addWidget(self.listStyles)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.labelDesktopType = QtGui.QLabel(styleWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.labelDesktopType.setFont(font)
        self.labelDesktopType.setStyleSheet(_fromUtf8(""))
        self.labelDesktopType.setObjectName(_fromUtf8("labelDesktopType"))
        self.verticalLayout_3.addWidget(self.labelDesktopType)
        self.comboBoxDesktopType = QtGui.QComboBox(styleWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(10)
        self.comboBoxDesktopType.setFont(font)
        self.comboBoxDesktopType.setStyleSheet(_fromUtf8(""))
        self.comboBoxDesktopType.setObjectName(_fromUtf8("comboBoxDesktopType"))
        self.comboBoxDesktopType.addItem(_fromUtf8(""))
        self.comboBoxDesktopType.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBoxDesktopType)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.labelDesktopNumbers = QtGui.QLabel(styleWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.labelDesktopNumbers.setFont(font)
        self.labelDesktopNumbers.setStyleSheet(_fromUtf8(""))
        self.labelDesktopNumbers.setObjectName(_fromUtf8("labelDesktopNumbers"))
        self.verticalLayout_2.addWidget(self.labelDesktopNumbers)
        self.spinBoxDesktopNumbers = QtGui.QSpinBox(styleWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(10)
        self.spinBoxDesktopNumbers.setFont(font)
        self.spinBoxDesktopNumbers.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBoxDesktopNumbers.setStyleSheet(_fromUtf8(""))
        self.spinBoxDesktopNumbers.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxDesktopNumbers.setMinimum(1)
        self.spinBoxDesktopNumbers.setObjectName(_fromUtf8("spinBoxDesktopNumbers"))
        self.verticalLayout_2.addWidget(self.spinBoxDesktopNumbers)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 2)
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 3, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 2, 2, 1, 1)

        self.retranslateUi(styleWidget)
        QtCore.QMetaObject.connectSlotsByName(styleWidget)

    def retranslateUi(self, styleWidget):
        styleWidget.setWindowTitle(kdecore.i18n("Themes"))
        styleWidget.setStyleSheet(kdecore.i18n("color: rgb(234, 225, 228);"))
        self.label.setText(kdecore.i18n("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; font-weight:600;\">Customize Your Desktop</span></p></body></html>"))
        self.labelMouseDesc.setText(kdecore.i18n("Choose your favorite theme and desktop type. Customize the blackPanther OS with colorful styles and themes."))
        self.labelDesktopType.setText(kdecore.i18n("Desktop Type"))
        self.comboBoxDesktopType.setItemText(0, kdecore.i18n("Desktop view (KDE4 Style)"))
        self.comboBoxDesktopType.setItemText(1, kdecore.i18n("Folder view (KDE3 Style)"))
        self.labelDesktopNumbers.setText(kdecore.i18n("Number of Desktops"))


def encode(text):
    return text.encode('utf-8')
    