#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ServiceItemWidget(object):
    def setupUi(self, ServiceItemWidget):
        ServiceItemWidget.setObjectName(_fromUtf8("ServiceItemWidget"))
        ServiceItemWidget.resize(505, 95)
        ServiceItemWidget.setMinimumSize(QtCore.QSize(0, 90))
        self.gridLayout = QtGui.QGridLayout(ServiceItemWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelStatus = QtGui.QLabel(ServiceItemWidget)
        self.labelStatus.setMinimumSize(QtCore.QSize(111, 90))
        self.labelStatus.setMaximumSize(QtCore.QSize(111, 90))
        self.labelStatus.setText(_fromUtf8(""))
        self.labelStatus.setPixmap(QtGui.QPixmap(_fromUtf8("./module_gui/pics/logo2010.png")))
        self.labelStatus.setScaledContents(True)
        self.labelStatus.setObjectName(_fromUtf8("labelStatus"))
        self.gridLayout.addWidget(self.labelStatus, 0, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(15, 5, 15, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.labelName = QtGui.QLabel(ServiceItemWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.labelName.setFont(font)
        self.labelName.setObjectName(_fromUtf8("labelName"))
        self.verticalLayout.addWidget(self.labelName)
        self.labelDesc = QtGui.QLabel(ServiceItemWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(10)
        self.labelDesc.setFont(font)
        self.labelDesc.setStyleSheet(_fromUtf8(""))
        self.labelDesc.setObjectName(_fromUtf8("labelDesc"))
        self.verticalLayout.addWidget(self.labelDesc)
        self.labelSize = QtGui.QLabel(ServiceItemWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(10)
        self.labelSize.setFont(font)
        self.labelSize.setStyleSheet(_fromUtf8(""))
        self.labelSize.setObjectName(_fromUtf8("labelSize"))
        self.verticalLayout.addWidget(self.labelSize)
        self.widget = QtGui.QWidget(ServiceItemWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.message = QtGui.QLabel(self.widget)
        self.message.setText(_fromUtf8(""))
        self.message.setObjectName(_fromUtf8("message"))
        self.horizontalLayout.addWidget(self.message)
        self.installButton = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.installButton.sizePolicy().hasHeightForWidth())
        self.installButton.setSizePolicy(sizePolicy)
        self.installButton.setMinimumSize(QtCore.QSize(0, 20))
        self.installButton.setObjectName(_fromUtf8("installButton"))
        self.horizontalLayout.addWidget(self.installButton)
        self.verticalLayout.addWidget(self.widget)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)

        self.retranslateUi(ServiceItemWidget)
        QtCore.QMetaObject.connectSlotsByName(ServiceItemWidget)

    def retranslateUi(self, ServiceItemWidget):
        ServiceItemWidget.setWindowTitle(kdecore.i18n("Form"))
        self.labelStatus.setStyleSheet(kdecore.i18n("border: 1px solid rgb(236, 236, 236, 100);"))
        self.labelName.setText(kdecore.i18n("appName"))
        self.labelDesc.setText(kdecore.i18n("appDesc"))
        self.labelSize.setText(kdecore.i18n("appSize"))
        self.installButton.setText(kdecore.i18n("Install"))


def encode(text):
    return text.encode('utf-8')
    