#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from wallpaperWidget_wrap.ui on Sat Jul 12 19:01:38 2014
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_wallpaperWidget(object):
    def setupUi(self, wallpaperWidget):
        wallpaperWidget.setObjectName(_fromUtf8("wallpaperWidget"))
        wallpaperWidget.resize(586, 542)
        self.gridLayout = QtGui.QGridLayout(wallpaperWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.listWallpaper = QtGui.QListWidget(wallpaperWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWallpaper.sizePolicy().hasHeightForWidth())
        self.listWallpaper.setSizePolicy(sizePolicy)
        self.listWallpaper.setMinimumSize(QtCore.QSize(0, 0))
        self.listWallpaper.setStyleSheet(_fromUtf8("#listWallpaper{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 81), stop:0.00537634 rgba(0, 0, 0, 80), stop:1 rgba(250, 250, 230, 80));\n"
"\n"
"border: 1px solid rgb(236, 236, 236, 80);}"))
        self.listWallpaper.setFrameShape(QtGui.QFrame.NoFrame)
        self.listWallpaper.setFrameShadow(QtGui.QFrame.Sunken)
        self.listWallpaper.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.listWallpaper.setAlternatingRowColors(False)
        self.listWallpaper.setTextElideMode(QtCore.Qt.ElideRight)
        self.listWallpaper.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.listWallpaper.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.listWallpaper.setMovement(QtGui.QListView.Static)
        self.listWallpaper.setFlow(QtGui.QListView.LeftToRight)
        self.listWallpaper.setProperty(_fromUtf8("isWrapping"), True)
        self.listWallpaper.setResizeMode(QtGui.QListView.Adjust)
        self.listWallpaper.setLayoutMode(QtGui.QListView.SinglePass)
        self.listWallpaper.setSpacing(0)
        self.listWallpaper.setGridSize(QtCore.QSize(170, 180))
        self.listWallpaper.setViewMode(QtGui.QListView.IconMode)
        self.listWallpaper.setModelColumn(0)
        self.listWallpaper.setUniformItemSizes(True)
        self.listWallpaper.setBatchSize(1)
        self.listWallpaper.setWordWrap(True)
        self.listWallpaper.setSelectionRectVisible(True)
        self.listWallpaper.setObjectName(_fromUtf8("listWallpaper"))
        self.verticalLayout.addWidget(self.listWallpaper)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.buttonChooseWp = QtGui.QPushButton(wallpaperWidget)
        self.buttonChooseWp.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(10)
        self.buttonChooseWp.setFont(font)
        self.buttonChooseWp.setObjectName(_fromUtf8("buttonChooseWp"))
        self.horizontalLayout.addWidget(self.buttonChooseWp)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.checkBox = QtGui.QCheckBox(wallpaperWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 5, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 5, 2, 1, 1)
        self.labelMouseDesc = QtGui.QLabel(wallpaperWidget)
        self.labelMouseDesc.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(11)
        self.labelMouseDesc.setFont(font)
        self.labelMouseDesc.setStyleSheet(_fromUtf8(""))
        self.labelMouseDesc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelMouseDesc.setWordWrap(True)
        self.labelMouseDesc.setObjectName(_fromUtf8("labelMouseDesc"))
        self.gridLayout.addWidget(self.labelMouseDesc, 3, 1, 1, 1)
        self.label = QtGui.QLabel(wallpaperWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(25)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8(""))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem5, 2, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 6, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem7, 4, 1, 1, 1)

        self.retranslateUi(wallpaperWidget)
        QtCore.QMetaObject.connectSlotsByName(wallpaperWidget)

    def retranslateUi(self, wallpaperWidget):
        wallpaperWidget.setWindowTitle(kdecore.i18n("Wallpaper"))
        wallpaperWidget.setStyleSheet(kdecore.i18n("color: rgb(234, 225, 228);"))
        self.buttonChooseWp.setText(kdecore.i18n("Choose wallpaper from file"))
        self.checkBox.setText(kdecore.i18n("Don\'t change wallpaper"))
        self.labelMouseDesc.setText(kdecore.i18n("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'URW Gothic L\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Choose your favorite wallpaper for blackPanther OS. Don\'t forget to check out <span style=\" font-weight:600;\">Desktop Settings</span> for downloading new and cool wallpapers.</p></body></html>"))
        self.label.setText(kdecore.i18n("Choose a Wallpaper"))


def encode(text):
    return text.encode('utf-8')
    