#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from main.ui on Fri Jul  4 21:06:28 2014
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MigrationUI(object):
    def setupUi(self, MigrationUI):
        MigrationUI.setObjectName(_fromUtf8("MigrationUI"))
        MigrationUI.resize(700, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/raw/pics/cr64-app-migration.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MigrationUI.setWindowIcon(icon)
        MigrationUI.setStyleSheet(_fromUtf8("#migration{\n"
"    \n"
"       background-image:url(\':/raw/pics/bg.png\');\n"
"       background-repeat: no-repeat;\n"
"       background-position: left top;\n"
"       background-color: #262C3B;\n"
"       alternate-background-color: gray;\n"
"       selection-background-color: gray;\n"
"\n"
"}\n"
"\n"
"QStackedWidget#mainStack {\n"
"    color: white;\n"
"     border-style: outset;\n"
"     border-width: 1px;\n"
"     border-radius: 10px;\n"
"     border-color: rgba(255, 255, 255, 50);\n"
"\n"
"}\n"
"\n"
""))
        self.gridLayout_3 = QtGui.QGridLayout(MigrationUI)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.migration = QtGui.QWidget(MigrationUI)
        self.migration.setObjectName(_fromUtf8("migration"))
        self.gridLayout_2 = QtGui.QGridLayout(self.migration)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelLogo = QtGui.QLabel(self.migration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLogo.sizePolicy().hasHeightForWidth())
        self.labelLogo.setSizePolicy(sizePolicy)
        self.labelLogo.setMinimumSize(QtCore.QSize(130, 80))
        self.labelLogo.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelLogo.setText(_fromUtf8(""))
        self.labelLogo.setPixmap(QtGui.QPixmap(_fromUtf8(":/raw/pics/migrationlogo.png")))
        self.labelLogo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelLogo.setMargin(0)
        self.labelLogo.setIndent(5)
        self.labelLogo.setObjectName(_fromUtf8("labelLogo"))
        self.gridLayout.addWidget(self.labelLogo, 0, 0, 1, 2)
        self.labelMenu = QtGui.QLabel(self.migration)
        self.labelMenu.setMinimumSize(QtCore.QSize(130, 130))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Luxi Sans"))
        font.setPointSize(11)
        self.labelMenu.setFont(font)
        self.labelMenu.setAutoFillBackground(False)
        self.labelMenu.setStyleSheet(_fromUtf8("color: rgb(38, 44, 59);"))
        self.labelMenu.setText(_fromUtf8(""))
        self.labelMenu.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelMenu.setIndent(5)
        self.labelMenu.setObjectName(_fromUtf8("labelMenu"))
        self.gridLayout.addWidget(self.labelMenu, 2, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.mainStack = QtGui.QStackedWidget(self.migration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainStack.sizePolicy().hasHeightForWidth())
        self.mainStack.setSizePolicy(sizePolicy)
        self.mainStack.setStyleSheet(_fromUtf8("QStackedWidget#mainStack{background-color:rgba(255, 255, 255,200);\n"
"margin: 10px;\n"
"}"))
        self.mainStack.setObjectName(_fromUtf8("mainStack"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.mainStack.addWidget(self.page)
        self.verticalLayout_4.addWidget(self.mainStack)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.buttonCancel = QtGui.QPushButton(self.migration)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.buttonCancel.setFont(font)
        self.buttonCancel.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.buttonCancel.setObjectName(_fromUtf8("buttonCancel"))
        self.horizontalLayout_2.addWidget(self.buttonCancel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.buttonBack = QtGui.QPushButton(self.migration)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.buttonBack.setFont(font)
        self.buttonBack.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.buttonBack.setObjectName(_fromUtf8("buttonBack"))
        self.horizontalLayout_2.addWidget(self.buttonBack)
        self.buttonNext = QtGui.QPushButton(self.migration)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.buttonNext.setFont(font)
        self.buttonNext.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.buttonNext.setObjectName(_fromUtf8("buttonNext"))
        self.horizontalLayout_2.addWidget(self.buttonNext)
        self.buttonFinish = QtGui.QPushButton(self.migration)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.buttonFinish.setFont(font)
        self.buttonFinish.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.buttonFinish.setObjectName(_fromUtf8("buttonFinish"))
        self.horizontalLayout_2.addWidget(self.buttonFinish)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.gridLayout_3.addWidget(self.migration, 0, 0, 1, 1)

        self.retranslateUi(MigrationUI)
        self.mainStack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MigrationUI)

    def retranslateUi(self, MigrationUI):
        MigrationUI.setWindowTitle(kdecore.i18n("Migration Tool"))
        self.buttonCancel.setText(kdecore.i18n("Cancel"))
        self.buttonBack.setText(kdecore.i18n("Back"))
        self.buttonNext.setText(kdecore.i18n("Next"))
        self.buttonFinish.setText(kdecore.i18n("Finish"))

import raw_rc

def encode(text):
    return text.encode('utf-8')
    