#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from src/migration/gui/ui/summaryWidget.ui on Fri Jul  4 12:37:32 2014
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_summaryWidget(object):
    def setupUi(self, summaryWidget):
        summaryWidget.setObjectName(_fromUtf8("summaryWidget"))
        summaryWidget.resize(615, 375)
        self.gridLayout = QtGui.QGridLayout(summaryWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.textSummary = QtGui.QTextEdit(summaryWidget)
        self.textSummary.setObjectName(_fromUtf8("textSummary"))
        self.gridLayout.addWidget(self.textSummary, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.labelProfilerIntro = QtGui.QLabel(summaryWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelProfilerIntro.sizePolicy().hasHeightForWidth())
        self.labelProfilerIntro.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.labelProfilerIntro.setFont(font)
        self.labelProfilerIntro.setStyleSheet(_fromUtf8("color: white"))
        self.labelProfilerIntro.setFrameShadow(QtGui.QFrame.Raised)
        self.labelProfilerIntro.setWordWrap(True)
        self.labelProfilerIntro.setObjectName(_fromUtf8("labelProfilerIntro"))
        self.verticalLayout.addWidget(self.labelProfilerIntro)
        self.gridLayout.addLayout(self.verticalLayout, 2, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 3, 1, 1, 1)

        self.retranslateUi(summaryWidget)
        QtCore.QMetaObject.connectSlotsByName(summaryWidget)

    def retranslateUi(self, summaryWidget):
        summaryWidget.setWindowTitle(kdecore.i18n("Summary"))
        self.labelProfilerIntro.setText(kdecore.i18n("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Your settings will be applied in next screen...</span></p></body></html>"))


def encode(text):
    return text.encode('utf-8')
    