#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from src/migration/gui/ui/userFilesWidget.ui on Fri Jul  4 12:37:32 2014
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_userFilesWidget(object):
    def setupUi(self, userFilesWidget):
        userFilesWidget.setObjectName(_fromUtf8("userFilesWidget"))
        userFilesWidget.resize(571, 385)
        self.verticalLayout = QtGui.QVBoxLayout(userFilesWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.nothing = QtGui.QRadioButton(userFilesWidget)
        self.nothing.setToolTip(_fromUtf8(""))
        self.nothing.setChecked(True)
        self.nothing.setObjectName(_fromUtf8("nothing"))
        self.gridLayout.addWidget(self.nothing, 0, 0, 1, 1)
        self.link = QtGui.QRadioButton(userFilesWidget)
        self.link.setEnabled(True)
        self.link.setToolTip(_fromUtf8(""))
        self.link.setObjectName(_fromUtf8("link"))
        self.gridLayout.addWidget(self.link, 1, 0, 1, 1)
        self.copy = QtGui.QRadioButton(userFilesWidget)
        self.copy.setEnabled(True)
        self.copy.setToolTip(_fromUtf8(""))
        self.copy.setObjectName(_fromUtf8("copy"))
        self.gridLayout.addWidget(self.copy, 2, 0, 1, 1)
        self.destination = QtGui.QLineEdit(userFilesWidget)
        self.destination.setEnabled(False)
        self.destination.setObjectName(_fromUtf8("destination"))
        self.gridLayout.addWidget(self.destination, 2, 1, 1, 1)
        self.dirview = QtGui.QTreeWidget(userFilesWidget)
        self.dirview.setEnabled(False)
        self.dirview.setObjectName(_fromUtf8("dirview"))
        self.gridLayout.addWidget(self.dirview, 3, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(userFilesWidget)
        QtCore.QMetaObject.connectSlotsByName(userFilesWidget)

    def retranslateUi(self, userFilesWidget):
        userFilesWidget.setWindowTitle(kdecore.i18n("Form"))
        self.nothing.setText(kdecore.i18n("Do Nothing"))
        self.link.setText(kdecore.i18n("Put links to my desktop"))
        self.copy.setText(kdecore.i18n("Copy files to directory :"))
        self.destination.setText(kdecore.i18n("~/Desktop"))
        self.dirview.headerItem().setText(0, kdecore.i18n("Directory"))
        self.dirview.headerItem().setText(1, kdecore.i18n("Size"))


def encode(text):
    return text.encode('utf-8')
    