#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from src/migration/gui/ui/usersItemWidget.ui on Fri Jul  4 12:37:34 2014
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_usersItemWidget(object):
    def setupUi(self, usersItemWidget):
        usersItemWidget.setObjectName(_fromUtf8("usersItemWidget"))
        usersItemWidget.resize(418, 52)
        usersItemWidget.setWindowTitle(_fromUtf8("ItemWidget"))
        usersItemWidget.setStyleSheet(_fromUtf8(""))
        self.gridLayout = QtGui.QGridLayout(usersItemWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkState = QtGui.QCheckBox(usersItemWidget)
        self.checkState.setText(_fromUtf8(""))
        self.checkState.setObjectName(_fromUtf8("checkState"))
        self.gridLayout.addWidget(self.checkState, 0, 0, 1, 1)
        self.labelIcon = QtGui.QLabel(usersItemWidget)
        self.labelIcon.setMinimumSize(QtCore.QSize(32, 32))
        self.labelIcon.setMaximumSize(QtCore.QSize(32, 32))
        self.labelIcon.setText(_fromUtf8(""))
        self.labelIcon.setObjectName(_fromUtf8("labelIcon"))
        self.gridLayout.addWidget(self.labelIcon, 0, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.userName = QtGui.QLabel(usersItemWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userName.sizePolicy().hasHeightForWidth())
        self.userName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.userName.setFont(font)
        self.userName.setStyleSheet(_fromUtf8(""))
        self.userName.setText(_fromUtf8("userName"))
        self.userName.setObjectName(_fromUtf8("userName"))
        self.verticalLayout.addWidget(self.userName)
        self.partition = QtGui.QLabel(usersItemWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.partition.sizePolicy().hasHeightForWidth())
        self.partition.setSizePolicy(sizePolicy)
        self.partition.setStyleSheet(_fromUtf8(""))
        self.partition.setText(_fromUtf8("partition"))
        self.partition.setWordWrap(True)
        self.partition.setObjectName(_fromUtf8("partition"))
        self.verticalLayout.addWidget(self.partition)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)

        self.retranslateUi(usersItemWidget)
        QtCore.QMetaObject.connectSlotsByName(usersItemWidget)

    def retranslateUi(self, usersItemWidget):
        self.checkState.setToolTip(kdecore.i18n("Set or unset entry as default boot entry."))


def encode(text):
    return text.encode('utf-8')
    